pages_build_output_dir = "./" 
name = "cloudflare-imgbed"
compatibility_date = "2025-04-20"

[[kv_namespaces]]
binding = "img_url"
id = "03f443c34baf40e2ab171732bcf85479"

[[r2_buckets]]
binding = "img_r2"
bucket_name = "img-r2"
